language: go
sudo: required

go:
  - 1.x

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - cd vendor/github.com/google/brotli
  - ./configure-cmake
  - make && sudo make install
  - cd ../../../..
  - go test ./cache
  - go test ./config
  - go test ./director
  - go test ./dispatch
  - go test ./httplog
  - go test ./performance
  - go test ./proxy
  - go test ./server
  - go test ./util
  - go test ./vars
