language: go

go:
  - 1.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/jteeuwen/go-bindata/...

script:
  - dep ensure
  - cd vendor/github.com/google/brotli
  - ./configure-cmake --prefix=.
  - make && make install
  - cd ../../../..
  - go-bindata -pkg server -o server/bindata.go assets/dist
  - go test ./cache
  - go test ./config
  - go test ./director
  - go test ./dispatch
  - go test ./httplog
  - go test ./performance
  - go test ./proxy
  - go test ./server
  - go test ./util
  - go test ./vars
