language: go
sudo: required

go:
  - "1.12"

script:
  - make test
  - docker build -t pike .

after_success:
  - export VERSION=2.0.0
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag pike $DOCKER_USERNAME/pike:$VERSION
  - docker push $DOCKER_USERNAME/pike:$VERSION
  - docker images
