# 程序监听的端口，默认为 :3015
listen: :3015

# 程序限制并发请求量
# concurrency: 256000

# 是否启用server timing
# enableServerTiming: true

# 生成请求唯一标记的配置，默认为 host method uri，建议使用默认配置
# identity: host method path proto scheme uri userAgent query ~jt >X-Token ?id

# 需要添加的自定义的响应头
header:
  # $env 从env中获取该值
  - "X-Server:$SERVER"
  - "X-Location:GZ"
# 需要添加的自定义请求头
requestHeader:
  # $env 从env中获取该值
  - "X-Server:$SERVER"
  - "X-Location:GZ"

compress:
  # 缓存数据压缩级别
  level: 0
  # 缓存数据压缩最少长度
  minLength: 1024
  # 压缩的筛选（只配置针对文件类型压缩，使用正则匹配）
  filter: "text|javascript|json"

# cache的相关配置
cache:
  # 缓存分区大小
  zone: 1024
  # 缓存每个分区的缓存大小
  size: 10240
  # 缓存hit for pass的时长
  hitForPass: 600

# 超时的相关配置
timeout:
  idleConn: 90s
  expectContinue: 1s
  responseHeader: 10s
  connect: 15s
  tlsHandshake: 5s
