name: pike
directors:
  -
    name: tiny 
    type: first 
    pass:
      - cache-control=no-cache
    ping: /ping
    host:
      - macmini:3015
    backends:
      - actp.aslant.site
  -
    name: timtam
    type: roundRobin
    ping: /ping
    prefix:
      - /dcharts
      - /tiny
    host:
      - dcharts.com
      - www.dcharts.com
    backends:
      - npmtrend.com