# HTTP response header 中的 Pike 
name: Pike
# 程序监听的端口，默认为 :3015
listen: :3015
# 数据缓存的db文件（必须指定）
db: /tmp/pike.cache
# 后台管理员页面路径，如果不配置，无法使用管理员功能
adminPath: /pike
# 管理员验证token
adminToken: ry3WwvhVG
# 生成请求唯一标记的配置，默认为 host method uri，建议使用默认配置
# identity: host method path proto scheme uri userAgent query ~jt >X-Token ?id
# 是否使用自动生成ETag（对于没有ETag的添加）
etag: true
# 是否启用server timing
enableServerTiming: false
# 设置对于数据压缩的最小文件（大于此值才压缩），如果设置为0，则使用默认值1024
compressMinLength: 1024
# 设置对于数据的压缩级别，如果设置为0，则使用golang默认值（建议使用）
compressLevel: 0
# 程序并发限制，设置为0表示使用默认值 (256 * 1024)
concurrency: 0
# 设置upstream的连接超时，默认为10s
connectTimeout: 10s 
# 过期缓存的清除时间间隔，如果设置为小于等于0 ，则使用默认值 300s
expiredClearInterval: 300s
# 访问日志的格式化，如果对于性能有更高的要求，而且也不需要访问日志，则不需要此配置
logFormat: "pike\t{when-iso-ms} - {client-ip} - \"{method} {uri}\" {status} {size} {latency-ms}ms"
# 访问日志保存路径
# accessLog: /tmp/pike/access.log
accessLog: udp://mac:7349
# accessLog: console
# accessLog: /tmp/pike
# 日志类型，如果为"date"表示按天分割日志，accessLog则应该配置为一个目录
logType: date
# 文本类型（Content-Type包含此类型字符串会被压缩）
# 若没有配置此参数则使用默认值：text javascript json
textTypes:
  - text
  - javascript
  - json
# 需要添加的自定义的响应头
header:
  # ${env} 从env中获取该值
  - "X-Server:${SERVER}"
  - "X-Location:GZ"
# 需要添加的自定义请求头
requestHeader:
  # ${env} 从env中获取该值
  - "X-Server:${SERVER}"
  - "X-Location:GZ"
# 需要做rewrite的url列表
# /old:/new
# /api/*:/$1
# /js/*":"/public/javascripts/$1
# /users/*/orders/*:/user/$1/order/$2
rewrites:
  -
    "/js/*:/public/javascripts/$1"
directors:
  -
    # 名称
    name: tiny 
    # backend的选择策略，支持 random roundRobin ipHash uriHash first header:field  cookie:name
    # 默认为 roundRobin
    policy: "cookie:jt"
    # backend的健康检测，如果不配置，则默认判断该端口是否被监听
    ping: /ping
    # prefix与host是AND的关系
    # 判断请求url的是否包含该前缀，如果是，则是此director
    prefixs:
      - /api
    rewrites:
      - "/api/*:/$1"
    # 判断请求的host是否符合，如果符合，则是此director
    # hosts:
    #   - mac:3015
    # 请求头，单独设置至此director（和全局header的配置方式一样）
    requestHeader:
      - "X-Version:${VERSION}" 
    header:
    # 响应头，单独设置至此director（和全局header的配置方式一样）
      - "X-Powered-By:koa"
    # backend列表
    backends:
      - http://127.0.0.1:5018
      - http://192.168.31.3:3001
      - http://192.168.31.3:3002
  -
    name: npmtrend
    # 根据header中的token选择backend
    policy: "header:Token" 
    ping: /ping
    hosts:
      - npmtrend.com
    backends:
      - http://192.168.31.3:3200
      - http://192.168.31.3:3300