# 程序监听的端口，默认为 :3015
listen: 127.0.0.1:3015

# 管理后台配置
admin:
  # 管理后台前缀
  prefix: /pike
  # 管理后台认证用户
  user: pike
  # 管理后台认证密码
  password: def

# 程序限制并发请求量
concurrency: 256000

# 是否启用server timing
enable_server_timing: true

# 生成请求唯一标记的配置，默认为 host method uri，建议无需要配置，使用默认值
identity: host method path proto scheme uri userAgent query ~jt >X-Token ?id

# 需要添加的自定义的响应头
header:
  # $env 从env中获取该值
  - "X-Server:$SERVER"
  - "X-Location:GZ"
# 需要添加的自定义请求头
request_header:
  # $env 从env中获取该值
  - "X-Server:$CLIENT"
  - "X-Location:GD"

compress:
  # 缓存数据压缩级别
  level: 8
  # 缓存数据压缩最少长度
  min_length: 2000
  # 压缩的筛选（只配置针对文件类型压缩，使用正则匹配）
  filter: "text|javascript|json|xml"

# cache的相关配置
cache:
  # 缓存分区大小
  zone: 1024
  # 缓存每个分区的缓存大小
  size: 10240
  # 缓存hit for pass的时长
  hit_for_pass: 600

# 超时的相关配置
timeout:
  idle_conn: 60s
  expect_continue: 2s
  response_header: 3s
  connect: 4s
  tls_handshake: 10s
